// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Challenge.Data.Models
{
    public partial class ProductDetail
    {
        public int ProductId { get; set; }
        public string Description { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string Observations { get; set; }

        public virtual Product Product { get; set; }
    }
}