// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Challenge.Data.Models
{
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Code { get; set; }
        public int State { get; set; }
        public int ProductTypeId { get; set; }

        public virtual ProductDetail ProductDetail { get; set; }
    }
}